//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8/7/2013 10:46:12 PM
namespace PunClient.PunService
{
    
    /// <summary>
    /// There are no comments for PunContext in the schema.
    /// </summary>
    public partial class PunContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PunContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PunContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Data", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("PunClient.PunService", typeName.Substring(4)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("PunClient.PunService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Data.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Puns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Pun> Puns
        {
            get
            {
                if ((this._Puns == null))
                {
                    this._Puns = base.CreateQuery<Pun>("Puns");
                }
                return this._Puns;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Pun> _Puns;
        /// <summary>
        /// There are no comments for Puns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPuns(Pun pun)
        {
            base.AddObject("Puns", pun);
        }
    }
    /// <summary>
    /// There are no comments for Data.Pun in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PunID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Puns")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PunID")]
    public partial class Pun : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Pun object.
        /// </summary>
        /// <param name="punID">Initial value of PunID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Pun CreatePun(int punID)
        {
            Pun pun = new Pun();
            pun.PunID = punID;
            return pun;
        }
        /// <summary>
        /// There are no comments for Property PunID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PunID
        {
            get
            {
                return this._PunID;
            }
            set
            {
                this.OnPunIDChanging(value);
                this._PunID = value;
                this.OnPunIDChanged();
                this.OnPropertyChanged("PunID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PunID;
        partial void OnPunIDChanging(int value);
        partial void OnPunIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Joke in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Joke
        {
            get
            {
                return this._Joke;
            }
            set
            {
                this.OnJokeChanging(value);
                this._Joke = value;
                this.OnJokeChanged();
                this.OnPropertyChanged("Joke");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Joke;
        partial void OnJokeChanging(string value);
        partial void OnJokeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
